// File generated by FlutterFire CLI.
// Manual modification is required if you haven't run flutterfire configure.
// This is a placeholder for compile-safety.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:1234567890:web:REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'sozotap-placeholder',
    authDomain: 'sozotap-placeholder.firebaseapp.com',
    storageBucket: 'sozotap-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:1234567890:android:REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'sozotap-placeholder',
    storageBucket: 'sozotap-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:1234567890:ios:REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'sozotap-placeholder',
    storageBucket: 'sozotap-placeholder.appspot.com',
    iosBundleId: 'com.example.sozotap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:1234567890:ios:REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'sozotap-placeholder',
    storageBucket: 'sozotap-placeholder.appspot.com',
    iosBundleId: 'com.example.sozotap',
  );
}
