// File generated by FlutterFire CLI.
// Manual modification is required if you haven't run flutterfire configure.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCaQ14ez5zu9T5r9mLA2cSJ9skjuWxSVM',
    appId: '1:628751053379:web:0900f9a09482e27e0cdaf6',
    messagingSenderId: '628751053379',
    projectId: 'sozotap',
    authDomain: 'sozotap.firebaseapp.com',
    storageBucket: 'sozotap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCaQ14ez5zu9T5r9mLA2cSJ9skjuWxSVM',
    appId: '1:628751053379:android:0900f9a09482e27e0cdaf6',
    messagingSenderId: '628751053379',
    projectId: 'sozotap',
    storageBucket: 'sozotap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCaQ14ez5zu9T5r9mLA2cSJ9skjuWxSVM',
    appId: '1:628751053379:ios:0900f9a09482e27e0cdaf6',
    messagingSenderId: '628751053379',
    projectId: 'sozotap',
    storageBucket: 'sozotap.firebasestorage.app',
    iosBundleId: 'com.sozotap.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCaQ14ez5zu9T5r9mLA2cSJ9skjuWxSVM',
    appId: '1:628751053379:ios:0900f9a09482e27e0cdaf6',
    messagingSenderId: '628751053379',
    projectId: 'sozotap',
    storageBucket: 'sozotap.firebasestorage.app',
    iosBundleId: 'com.sozotap.app',
  );
}
